### ISSUE TITLE
安装样式后贴吧无变化

### ISSUE THREAD

**Issue by Janzulene** [imaverickk/Tieba-Maverick-UserCSS#1]
### 问题描述
在 Stylus 安装过后页面没有发生变化，经过测试和排查不是 Stylus 的问题（其他样式能够正常应用），但是不清楚是哪里出现问题了
### 出现页面
> https://tieba.baidu.com
### 相关元素类名
> .tieba-element

**Comment by imaverickk** [comment]
Chrome, Firefox 均未重现，可以尝试在无痕模式单独启用stylus测试是否为扩展冲突。
