### ISSUE TITLE
[问题反馈] 无法展开回复

### ISSUE THREAD

**Issue by Smolder3955** [imaverickk/Tieba-Maverick-UserCSS#3]
### 问题描述
> 如题
### 出现页面
> https://tieba.baidu.com
### 相关元素类名
> .tieba-element

**Comment by imaverickk** [comment]
未重现，有具体页面提供？

**Comment by Smolder3955** [comment]
> 未重现，有具体页面提供？

可能是我浏览器的问题，Vivladi浏览器的兼容性实在太差了，Edge浏览器确实没有复现这个问题

**Comment by imaverickk** [comment]
Vivladi确实不在兼容的范围内，目前基本只对基于Chromium的浏览器兼容，Firefox次之。

**Comment by Smolder3955** [comment]
> Vivladi确实不在兼容的范围内，目前基本只对基于Chromium的浏览器兼容，Firefox次之。

Vivladi也是Chromium浏览器，但这玩意儿小毛病是真的多，要不是为了安卓手机同步功能我也不想用，安卓版Edge实在太卡受不了，如果有兴趣可以试试这个浏览器

**Comment by imaverickk** [comment]
> > Vivladi确实不在兼容的范围内，目前基本只对基于Chromium的浏览器兼容，Firefox次之。
> 
> Vivladi也是Chromium浏览器，但这玩意儿小毛病是真的多，要不是安卓版Edge太卡我也不想用，如果有兴趣可以试试

安卓端用网页版贴吧吗，这个确实太小众了，不过样式一般不会对功能产生影响，可以禁用样式确认下是不是贴吧本身的兼容问题。

**Comment by Smolder3955** [comment]
> > > Vivladi确实不在兼容的范围内，目前基本只对基于Chromium的浏览器兼容，Firefox次之。
> > 
> > 
> > Vivladi也是Chromium浏览器，但这玩意儿小毛病是真的多，要不是安卓版Edge太卡我也不想用，如果有兴趣可以试试
> 
> 安卓端用网页版贴吧吗，这个确实太小众了，不过样式一般不会对功能产生影响，可以禁用样式确认下是不是贴吧本身的兼容问题。

就是Windows版本的Vivaldi浏览器，我手机都是旗舰配置，然而Edge不管是安卓版还是iOS都卡的不得了，功能也少得可怜非常难用，所以手机才换了Vivaldi浏览器，为了同步书签和历史记录不得不把电脑浏览器也换成Vivaldi，然后这浏览器桌面版毛病实在太多了，就算都是Chromium兼容性也属于差的那一档
