### ISSUE TITLE
贴吧图标显示不全

### ISSUE THREAD

**Issue by xiaolousir** [imaverickk/Tieba-Maverick-UserCSS#4]
### 问题描述
> 贴吧主页和帖子内图标显示不全
### 出现页面
> https://tieba.baidu.com

![123](https://github.com/user-attachments/assets/2d81785c-6082-4910-aaca-dd4e29854293)

**Comment by imaverickk** [comment]
检查fonts.gstatic.com是否可以正常访问

**Comment by xiaolousir** [comment]
> 检查[fonts.gstatic.com](http://fonts.gstatic.com)是否可以正常访问

错误
您所请求的网址（URL）无法获取
当尝试取回该 URL 时遇到下面的错误：http://fonts.gstatic.com/

访问被拒绝。

Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.

缓存服务器的管理员 root.

**Comment by imaverickk** [comment]
检查是否可以正常访问
fonts.gstatic.com/s/materialicons/v126/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2

**Comment by xiaolousir** [comment]
> 检查是否可以正常访问 [fonts.gstatic.com/s/materialicons/v126/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2](http://fonts.gstatic.com/s/materialicons/v126/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2)

错误
您所请求的网址（URL）无法获取
当尝试取回该 URL 时遇到下面的错误：http://fonts.gstatic.com/s/materialicons/v126/flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2

访问被拒绝。

Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.

缓存服务器的管理员 root.


已由 hk-api (squid/5.5) 生成 Fri, 23 Aug 2024 08:57:50 GMT
