### ISSUE TITLE
是否可以支持手机端呢

### ISSUE THREAD

**Issue by Wei-Winter** [imaverickk/Tieba-Maverick-UserCSS#5]
挺好用的！电脑上使用时界面非常美观。最近在手机上刷贴吧比较多，不知道能不能支持手机页面？自定义选项那么多，很繁琐的话那就算了～

**Comment by imaverickk** [comment]
手机上应该没有人用网页端吧，手机客户端的界面足够好了。

**Comment by Wei-Winter** [comment]
手机端的贴吧真是依托💩，不管是安卓还是iOS都特别卡，网页用着还算舒服，搭配此脚本
https://greasyfork.org/zh-CN/scripts/418349-移动端-百度系优化
